amqp:
  host: ${AMQP_RABBITMQ_HOST}
  port: ${AMQP_RABBITMQ_PORT}
  username: ${AMQP_RABBITMQ_USERNAME}
  password: ${AMQP_RABBITMQ_PASSWORD}
  admin:
    auto-create: true

keycloak:
  host: ${KEYCLOAK_HOST}
  realm: ${KEYCLOAK_REALM}

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL:localhost:3306}