services:
  app:
    container_name: adm_videos_app
    build:
      context: ../..
      dockerfile: dev.dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    networks:
      - adm_videos_network
      - adm_videos_services
networks:
  adm_videos_network:
  adm_videos_services:
    external: true