services:
#  app:
#    container_name: adm_videos_app
#    build: ../..
#    profiles:
#      - app
#    ports:
#      - "8080:8080"
#    env_file:
#      - ../../.env
#    networks:
#      - adm_videos_network

  mysql:
    container_name: adm_videos_mysql1
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
      - MYSQL_ROOT_HOST=%
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    volumes:
      - ../.docker/mysql:/var/lib/mysql:rw
    networks:
      - adm_videos_network

  rabbitmq:
    container_name: adm_videos_rabbitmq1
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBIRMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - adm_videos_network

  keycloack:
    container_name: adm_videos_keycloak1
#    image: quay.io/keycloak/keycloak:20.0.3
    image: quay.io/keycloak/keycloak:26.1.4-0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8443:8080"
    command:
      - start-dev
    volumes:
      - ../.docker/keycloak:/opt/keycloak/data/h2:rw
    networks:
      - adm_videos_network

networks:
  adm_videos_network: