name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - 'hotfix/**'
      - 'release/**'
  workflow_dispatch:

env:
  IMAGE_NAME: brunno98/fc3-admin-catalogo

jobs:
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # configuração dos passos do nosso job
    steps:
      # 1. Check-out do codigo fonte
      - uses: actions/checkout@v3
      # 2. configurar a JDK na maquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. exectutar os testes da aplicação
      - name: Run application tests
        run: ./gradlew test
  # Job para buildar a aplicação
  build:
    name: Build runner
    needs: tests
    runs-on: ubuntu-latest
    # configuração dos passos do nosso job
    steps:
      # 1. Check-out do codigo fonte
      - uses: actions/checkout@v3
      # 2. configurar a JDK na maquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Valida a existencia de gradle wrapper
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3.5.0
      # 4. Realizar o bulild da aplicação
      - name: Build da aplicação
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: clean build -x test
      # 5. Definir a variavel branch name
      - name: set BUILD_TAG
        run: |
          echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
      # 6. print BUILD_TAG
      - name: Print BUILD_TAG defined
        run: |
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run Number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"
      # 7. Log in Docker hub
      - name: Log in Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      # 8. Build & Deploy da imagem
      - name: Build & Deploy da imagem do docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}