name: CI pipeline

on:
  push:
    branches:
      - 'feature/**'
      - 'modulos/**'
  # Habilita o gatilho manual na UI do github
  workflow_dispatch:

jobs:
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # configuração dos passos do nosso job
    steps:
      # 1. Check-out do codigo fonte
      - uses: actions/checkout@v3
      # 2. configurar a JDK na maquina
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. exectutar os testes da aplicação
      - name: Run application tests
        run: ./gradlew test